# Generated by Django 3.1.6 on 2021-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stanica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.CharField(max_length=200)),
                ('duzina', models.CharField(max_length=100)),
                ('sirina', models.CharField(max_length=100)),
            ],
        ),
    ]
