# Generated by Django 3.1.6 on 2021-02-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stanica',
            old_name='duzina',
            new_name='tacka',
        ),
        migrations.RemoveField(
            model_name='stanica',
            name='sirina',
        ),
    ]
