# Generated by Django 3.1.6 on 2021-02-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_linija_uslov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linija',
            name='broj_stanica',
        ),
    ]
